config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root "home#index"

  # root "games#index"  # Set the root path to the game index
  resources :games do
    member do
      patch :save_score
      post :update # For card clicks
    end
  end

  get "/how-to-play", to: "home#how_to_play"
  get "/leaderboard", to: "home#leaderboard"

  # resources :cards, only: [ :index ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user, dependent: :destroy
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games, dependent: :destroy

  has_one_attached :profile_picture

  # validates :first_name, :last_name, presence: true
  # validates :age, numericality: { only_integer: true, greater_than: 0 }, allow_nil: true
  # validates :profile_picture, content_type: [ "image/png", "image/jpg", "image/jpeg" ], size: { less_than: 5.megabytes }, allow_nil: true

  def display_profile_picture
    profile_picture.attached? ? profile_picture : "bluey.png"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [ :show ]
  before_action :set_game, only: [ :show, :update ]

  def index
  end

  def create
    @game = current_user.games.new(score: 0, best_score: 0) # initialize def scores

    if @game.save
      redirect_to game_path(@game)
    else
      render json: { success: false, errors: @game.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def show
    @game = Game.find(params[:id])
    @cards = Card.all.shuffle
    # puts "Cards loaded for game: #{@cards.inspect}" # Debugging line
  end

  def update
    if @game.update(game_params)
      render json: { success: true, game: @game }
    else
      render json: { success: false, errors: @game.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def save_score
    game = current_user.games.find(params[:id])
    current_score = params[:score].to_i

    if game.update(score: current_score, best_score: [ game.best_score, current_score ].max)
      render json: { success: true }
    else
      render json: { success: false, errors: game.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private
  def game_params
    params.require(:game).permit(:score, :best_score)
  end

  def set_game
    @game = Game.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @instructions = "Click on a card to earn points, but be careful—once you click a card, you can't click it again! Can you remember where your favorite characters are hidden?"
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  # POST /users
  def create
    super do |resource|
      # attach profile picture if it's present
      resource.profile_picture.attach(params[:user][:profile_picture]) if params[:user][:profile_picture].present?

      flash[:notice] = "Welcome! You have signed up successfully." if is_navigational_format?
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :first_name, :last_name, :age, :profile_picture ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :first_name, :last_name, :age, :profile_picture ])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # POST /users/sign_in
  def create
    super do |resource|
      flash[:notice] = "Successfully logged in!" if is_navigational_format?
    end
  end

  # DELETE /users/sign_out
  def destroy
    flash[:notice] = "Successfully logged out!" if is_navigational_format?
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/games/show.html.erb
<div id="game-container" data-controller="game" data-game-id="<%= @game.id %>">
  <div id="game-header">
    <div class="player-profile">
      <% if @user.present? && @user.profile_picture.attached? %>
        <%= image_tag @user.display_profile_picture, class: "profile-picture" %>
      <% else %>
        <%= image_tag "bluey.png", class: "profile-picture" %>
      <% end %>
      <div class="player-info">
        <h3><%= current_user.first_name %> <%= current_user.last_name %></h3>
        <p>Age: <%= current_user.age %></p>
      </div>
    </div>

    <div id="scoreboard">
      <h2>Scoreboard</h2>
      <div>
        Score:
        <span data-target="game.score">0</span>
      </div>
      <div>
        Best Score:
        <span data-target="game.bestScore">0</span>
      </div>
    </div>
  </div>

  <br>

  <div id="game-board">
    <% @cards.each do |card| %>
      <div class="card" data-card-id="<%= card.id %>" data-action="click->game#clickCard" data-game-target="card">
        <img src="<%= asset_path(card.image_url) %>" alt="<%= card.name %>">
        <p><%= card.name %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div id="home-page">
  <h1>Welcome to the Bluey Character Memory Game! 🎉</h1>
  
  <div id="instructions" class="instructions">
    <h3><%= @instructions %></h3>
  </div>

  <div id="start-game-container" class="start-game-container">
    <%= link_to "Start Game", games_path, method: :post, class: "btn btn-primary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bluey Memory Game" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'rails-ujs', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'favicon.ico' %>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="wrapper">
      <div class="content">
        <%= render "shared/flash" %>

        <%= render "shared/header" %>

        <%= yield %>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<%= turbo_frame_tag :flash do %>
  <% flash.each do |type, message| %>
    <div data-controller="flash" data-action="click->flash#close_message" class="flash <%= type %>">
      <div class="d-flex align-items-center">
        <% if type == "alert" || type == "error" %>
          <i class="bi bi-exclamation-diamond-fill"></i>
        <% else %>
          <i class="bi bi-check-lg"></i>
        <% end %>
        <p class="m-0 ms-2"><%= message %></p>
      </div>
    </div>
  <% end %>

  <% flash.clear %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  Bluey Characters Reference: 
  <%= link_to 'https://www.bluey.tv/characters/', 'https://www.bluey.tv/characters/', target: '_blank', rel: 'noopener noreferrer' %>
</footer>

app/views/shared/_header.html.erb
<header class="navbar">
  <div class="navbar-container">
    <%= link_to "Bluey Memory Game", "#" , class: "navbar-brand" %>
    <nav class="navbar-links">
      <%= link_to "Home", "" , class: "navbar-link" %>
      <%= link_to "How to Play", "#" , class: "navbar-link" %>
      <%= link_to "Leaderboard", "#" , class: "navbar-link" %>
      <%= link_to "Profile", "#" , class: "navbar-link" %>
      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "navbar-link" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "navbar-link" %>
      <% end %>
    </nav>
  </div>
</header>